### ISSUE TITLE
Custom name output {name} gives original full path

### ISSUE THREAD

**Issue by jamespjh** [dexy/dexy#142]
From http://dexy.github.io/dexy-user-guide/

```
- output-name: "%(name)s-file.abc"
```

Gives:

```
./baz/1.txt -> ./baz/baz/1.txt-file.abc
```

I think this should be

```
./baz/1.txt -> ./baz/1.txt-file.abc
```

or even 

```
./baz/1.txt -> ./baz/1-file.abc
```

If this is working as intended, may I request that we add another couple of variables to the evaluation context for custom names to support this? I don't mind doing it...

**Comment by ananelson** [comment]
Hi, James,

I agree this is confusing. Currently there's a 'name', 'rootname' and 'dirname' available and also any variables defined in the 'environment' setting are also available. If the path starts with or contains a "/" it's passed through unaltered and the interpolation is applied, if it doesn't contain a "/" then it's assumed you want to keep that file in the current directory so the parent dir is added to the path. If you then use 'name' (rather than 'rootname') you get the full path twice.

So `output-name: "/%(name)s-file.abc"` should give you what you want, or `output-name: "%(rootname)-file.abc"`.

The `dexy/doc.py` code should probably look for %(name) in the output-name and skip applying the parent dir in this case. I'm also open to other suggestions for making name interpolation more intuitive.

**Comment by ananelson** [comment]
Also there should not be an internal `.txt` extension. Elsewhere in dexy I use `baserootname`.

**Comment by jamespjh** [comment]
Hi Ana,

Behaviour observed is:

for a file /hello/world.png
/bar/%(name)s.foo -> /bar/hello/world.png.foo
/bar/%(rootname)s.foo -> /bar/hello/world.foo

I would like to achieve -> /bar/world.foo

(i.e. just the leaf name, with my supplied extension and earlier path.)

**Comment by jamespjh** [comment]
See #143 for a pull request providing basename and baserootname
